/**
 * @generated by scripts/sync-tokens.mjs
 * Source: src/theme/tokens.json (Figma Variables export, bb-extract plugin)
 * Do not edit manually — re-run `npm run sync-tokens`.
 */

export const primitives = {
  color: {
    Ocean: "#0000ff",
    Milk: "#ffffff",
    Coffee: "#000000",
    Lime: "#33cc66",
    Amber: "#ffaa00",
    Cherry: "#e5384f",
  },
  spacing: {
    "1": 4,
    "2": 8,
    "3": 12,
    "4": 16,
    "5": 20,
    "6": 24,
    "7": 28,
    "8": 32,
  },
  radius: {
    none: 0,
    sm: 4,
    md: 8,
    lg: 16,
    full: 9999,
  },
  font: {
    family: {
      sans: "Inter",
      mono: "JetBrains Mono",
    },
    size: {
      xs: 12,
      sm: 14,
      md: 16,
      lg: 20,
      xl: 24,
      "2xl": 32,
      "3xl": 40,
    },
    weight: {
      regular: 400,
      medium: 500,
      bold: 700,
    },
    lineHeight: {
      tight: 1.2,
      normal: 1.5,
      loose: 1.75,
    },
  },
} as const;

export type Primitives = typeof primitives;
