/**
 * @generated by scripts/sync-tokens.mjs
 * Source: src/theme/tokens.json (Figma Variables export, bb-extract plugin)
 * Do not edit manually — re-run `npm run sync-tokens`.
 */

import { primitives } from './primitives';

export const lightSemantic = {
  palette: {
    background: primitives.color.Milk,
    text: primitives.color.Coffee,
    info: primitives.color.Ocean,
    success: primitives.color.Lime,
    warning: primitives.color.Amber,
    error: primitives.color.Cherry,
  },
} as const;

export const darkSemantic = {
  palette: {
    background: primitives.color.Coffee,
    text: primitives.color.Milk,
    info: primitives.color.Ocean,
    success: primitives.color.Lime,
    warning: primitives.color.Amber,
    error: primitives.color.Cherry,
  },
} as const;

export type Semantic = typeof lightSemantic;
