/**
 * Reads src/theme/tokens.json (Figma Variables export from the bb-extract plugin)
 * and writes:
 *   - src/theme/primitives.ts  (raw values)
 *   - src/theme/semantic.ts    (light + dark palettes, alias-resolved)
 *
 * Re-run via `npm run sync-tokens` after re-exporting from Figma.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const THEME_DIR = resolve(ROOT, 'src/theme');
const JSON_PATH = resolve(THEME_DIR, 'tokens.json');

const HEADER = `/**
 * @generated by scripts/sync-tokens.mjs
 * Source: src/theme/tokens.json (Figma Variables export, bb-extract plugin)
 * Do not edit manually — re-run \`npm run sync-tokens\`.
 */
`;

const data = JSON.parse(readFileSync(JSON_PATH, 'utf-8'));

const roundFloat = (n) => Math.round(n * 1e6) / 1e6;
const isIdent = (k) => /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(k);
const keyStr = (k) => (isIdent(k) ? k : JSON.stringify(k));

function isLeafToken(v) {
  return v && typeof v === 'object' && '$value' in v;
}

function walk(body, transformLeaf) {
  const out = {};
  for (const [k, v] of Object.entries(body)) {
    if (isLeafToken(v)) out[k] = transformLeaf(v);
    else if (v && typeof v === 'object') out[k] = walk(v, transformLeaf);
  }
  return out;
}

function literalForPrimitive(leaf) {
  let v = leaf.$value;
  if (typeof v === 'number') v = roundFloat(v);
  return { __literal: typeof v === 'string' ? JSON.stringify(v) : String(v) };
}

function literalForSemantic(leaf) {
  const v = leaf.$value;
  if (typeof v === 'string' && v.startsWith('{') && v.endsWith('}')) {
    const path = v.slice(1, -1).split('.');
    const expr = 'primitives' + path.map((p) =>
      isIdent(p) ? `.${p}` : `[${JSON.stringify(p)}]`
    ).join('');
    return { __literal: expr };
  }
  if (typeof v === 'number') return { __literal: String(roundFloat(v)) };
  return { __literal: JSON.stringify(v) };
}

function render(obj, level = 0) {
  if (obj && typeof obj === 'object' && '__literal' in obj) return obj.__literal;
  const pad = '  '.repeat(level + 1);
  const close = '  '.repeat(level);
  const entries = Object.entries(obj).map(
    ([k, v]) => `${pad}${keyStr(k)}: ${render(v, level + 1)}`
  );
  return `{\n${entries.join(',\n')},\n${close}}`;
}

const primCol = data.find((c) => c.name === 'Primitives');
const lightCol = data.find((c) => c.name === 'Semantic Light');
const darkCol = data.find((c) => c.name === 'Semantic Dark');
if (!primCol) throw new Error('Primitives collection missing in Tokens.json');
if (!lightCol || !darkCol) throw new Error('Semantic Light/Dark missing');

const primTree = walk(primCol.body, literalForPrimitive);
const lightTree = walk(lightCol.body, literalForSemantic);
const darkTree = walk(darkCol.body, literalForSemantic);

const primitivesTs = `${HEADER}
export const primitives = ${render(primTree)} as const;

export type Primitives = typeof primitives;
`;

const semanticTs = `${HEADER}
import { primitives } from './primitives';

export const lightSemantic = ${render(lightTree)} as const;

export const darkSemantic = ${render(darkTree)} as const;

export type Semantic = typeof lightSemantic;
`;

mkdirSync(THEME_DIR, { recursive: true });
writeFileSync(resolve(THEME_DIR, 'primitives.ts'), primitivesTs);
writeFileSync(resolve(THEME_DIR, 'semantic.ts'), semanticTs);

console.log('✓ src/theme/primitives.ts');
console.log('✓ src/theme/semantic.ts');
